### ISSUE TITLE
artoo.$ is not a function

### ISSUE THREAD

**Issue by angeloh** [medialab/artoo#225]
I am not sure what I did wrong. But I keep getting this error.

http://jsbin.com/puyeru/1/edit?html,js,output

**Comment by Yomguithereal** [comment]
Hello @angeloh,
`artoo.$ ` is not a function in your example because `artoo` is not supposed to be loaded from `head` but rather than from the bottom of `body` and in JSBin the example run weirdly.

Try to wrap your code thusly and it should work:

```js
artoo.on('ready', function() {
  // now artoo.$ is correctly set
});
```

There are some quirks concerning this particular point and I should fix them in a near future so that artoo usage in a dedicated page might be more straightforward.

**Comment by angeloh** [comment]
Thank you! It works.
