### ISSUE TITLE
How to scrape a content in a search page 

### ISSUE THREAD

**Issue by tarasprystavskyj** [medialab/artoo#250]
I need insert a search keyword. Then push a search button and scrape content
for a only one element - the count of results. 

In this website
https://www.rbauction.com/other?id=ci&s=Y2l8Tj0wJk50az1FcXVpcG1lbnQuZW4mTnR0PSZOdHg9

 I do it like this 
change search string:
$(".keyword-input-wrapper #rba-keyword-input").val("A40D");
submit a form:
$("form#rba-keyword-search")[0].submit();

and get data like this from the result. 
$("div.summary-result-container h2.float-left span#summary-result-count").text()

**Comment by boogheta** [comment]
Your problem is that submitting the form redirects you to a different page, hence you're losing the scope and need to reload artoo in the new page. You could use artoo's ajaxSpiders to collect the results from within you initial page, but it won't work as the resulting pages also load results dynamically individually.
You'll need some serverside scraper, you cane xperiment with [https://github./com/medialab/sandcrawler](sandcrawler) that runs artoo on a phantom engine, but note it's an alpha not completely documented project yet :/

**Comment by tarasprystavskyj** [comment]
thanks for reply.

2016-08-24 18:19 GMT+03:00 Benjamin Ooghe-Tabanou <notifications@github.com>
:
